version: '3'
services:
  springsql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=Lync123*
    volumes:
    - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    - "./db_data:/var/lib/mysql/"
  spring3:
    image: spring:v3
    depends_on:
    - springsql
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
    - jdbc.driverClassName=com.mysql.jdbc.Driver
    - jdbc.url=jdbc:mysql://springsql:3306/websystique
    - jdbc.username=root
    - jdbc.password=Lync123*
    - hibernate.dialect=org.hibernate.dialect.MySQLDialect
    - hibernate.show_sql=true
    - hibernate.format_sql=true
